#pragma config(Motor,  port2,           M_WHEEL_FR,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           M_WHEEL_BR,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           M_WHEEL_BL,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           M_WHEEL_FL,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int bound(int a, int amin, int amax){
	if(a <= amin) return amin;
	else if(a >= amax) return amax;
	else return a;
}

void move(int V, int H){
	motor[M_WHEEL_FL] = bound(V + H, -127, 127);
	motor[M_WHEEL_FR] = bound(V - H, -127, 127);
	motor[M_WHEEL_BL] = bound(V + H, -127, 127);
	motor[M_WHEEL_BR] = bound(V - H, -127, 127);
}

task main(){
	int V, H;

	while(true){
		V = vexRT[Ch3];
		H = vexRT[Ch1];

		move(V, H);

		wait1Msec(50);
	}
}
